title: Beyond Open Looks
description: "by: Keanu Ventura"
email: keventura@ucsd.edu
author: Keanu Ventura    
url: "https://keanuventura.github.io"

github_username:    KeanuVentura
linkedin_username: keanuventura

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
